name: feast
description: Feast - Your Meal Prep Companion

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_boxicons: ^3.0.0
  path: ^1.8.0
  numberpicker: ^2.1.2
  flutter_number_picker: ^1.0.1
  dotted_border: ^2.0.0+1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/recipes/
    - assets/recipes/recipe_list.json
  fonts:
    - family: CustomFont1
      fonts:
        - asset: fonts/hussarbd.otf

    - family: CustomFont2
      fonts:
        - asset: fonts/Poppins-Light.otf
